### PR TITLE
Fixed problems with coreg and coreg report when already coregistered

### PR DESCRIPTION
**Pull request by woolrich**
Fixed problems with coreg and coreg report when data has already been coregistered

### CODE REVIEW

**Comment by cgohil8** [comment]
@woolrich, if there's no issue would be good if you summarised the reason why you've created the pull request. E.g. for this one was it: "fiducials are not always available, e.g. for OPT data, so we only compute the distance to the fiducials if they exist"? This would help whoever's reviewing the pull request evaluate whether the code changes do what is intended.

Does this error arise when you do source reconstructed without any coreg? Because I think the coreg would error if you didn't have any fiducials.

**Comment by woolrich** [comment]
Yes - sorry - I had said I would rightly do this and then failed to!

Yes - "fiducials are not always needed for source reconstruction, e.g. with OPM data, so we only compute the distance to the fiducials if they exist"?

When working with OPM data, coreg() is called with the already_registered flag set, so that coreg() does the bare minimimum. However, that bare minimum crucially includes creating the necessary files in the format expected by source recon, and so coreg() does need to be called.

**Comment by cgohil8** [comment]
I see. A simpler fix might just be to only call `rhino.coreg_metrics` when `already_coregistered=False`. And handle `fid_err` not existing in the report code. I might tidy this up next time I'm working on this. Thanks.

**Comment by woolrich** [comment]
"handle fid_err not existing in the report code"
That bit is already done

**Pull request merged**
