### PR TITLE
New output directory structure

### PR DESCRIPTION
**Pull request by cgohil8**
**THIS PR IS NOT BACKWARDS COMPATIBLE.**
------------------------------------------------

Changes:
- Restructured the output directories/filenames.
  - The name of the subdirectories is specified via the `subjects` argument in `run_proc_batch` and `run_src_batch`.
- Renamed variables in the preproc and src batch processing to be more consistent.
- Updated examples within the repository.
- Can now load `.mff` EEG files.

## New output directory structure
```
outdir
   |-- sub-001_task-rest
        |-- beamform
        |-- bem
        |-- parc
        |-- rhino
        |    |-- coreg
        |    |-- surfaces
        |-- sub-001_task-rest_preproc_raw.fif
        |-- sub-001_task-rest_ica.fif
        |-- sub-001_task-rest_sflip_parc-raw.fif
   |-- sub-002_task-rest
        |-- ...
   |-- ...
   |-- logs
   |-- preproc_report
        |-- *.html
        |-- sub-001_task-rest
        |-- sub-002_task-rest
        |-- ...
   |-- src_report
        |-- *.html
        |-- sub-001_task-rest
        |-- sub-002_task-rest
        |-- ...
```

### CODE REVIEW

**Comment by cgohil8** [comment]
@matsvanes, it feels like generating the preproc is **much** slower with the latest changes?

**Comment by matsvanes** [comment]
@cgohil8 Would it be worth chaning "subject" to e.g. "session_name" as a more general term?

**Comment by cgohil8** [comment]
I think `subjects`/`subject` -> `sessions`/`session`, but this is a **huge** change.

**Comment by matsvanes** [comment]
@cgohil8 Can you have a look at the following?
- The subject name in the preproc report is now not matching with the actual subject name, because it's taken from the raw data. See https://github.com/OHBA-analysis/osl/blob/directory-restructure/osl/report/preproc_report.py#L124. So the solution would be to provide the subject name to this function
- In the src report, the report_data.pkl is generated/updated in the source recon (now subject) directory, and then copied over to the src report directory. This is actually not the case for preproc, where the report is generated (and updated) in the preproc report directory. I think it would make sense to only have the `report_data.pkl` in the report directory.

**Comment by matsvanes** [comment]
@cgohil8 and I also discussed whether we should include Maxfiltered data into this directory structure, but we decided against it for the following reasons:
- This would complicate things because then the subject directory name and the file name cannot use the same base. E.g., if we have a `sub001-run01_tsss.fif` and a `sub001-run01_trans.fif` file, we can't specify `sub001-run01` as a subject name because the preprocessed files would overwrite each other (and we often preprocess both - one for sensor, the other for source space analysis)
- Non-OHBA users and non Elekta users are probably not using `osl_maxfilter`, so for them the input data to osl preproc would be in a different directory structure anyway.
- Also keep in mind that at the moment, the maxfilter log files are saved next to the data, not in a logs directory.

**Comment by cgohil8** [comment]
> @cgohil8 Would it be worth chaning "subject" to e.g. "session_name" as a more general term?

We feeling brave enough to do `subject` -> `session`? I can attempt it with the source report changes. (Can't guarantee i'll catch everything though.)

**Comment by matsvanes** [comment]
@cgohil8 Wouldn't it make sense to make `preproc_files` optional in `run_src_batch`? i.e., if you have `subjects`, the preproc file is trivial, no (that is, in the OSL convention, e.g., `f"{subjects[0]}/{subjects[0]}_preproc_raw.fif"`)?

**Comment by cgohil8** [comment]
All functions (or virtually all of them) require the `preproc_file`. Hmmm, it's a interesting point now that we have a very well defined naming convention, it might be possible to get rid of `preproc_file`.

I think my preference would be to keep it, just because it allows the user to easily substitute a different preproc file in at the very last stage. E.g. if you source reconstructed already by then change the sensor level data, you can just feed the new preproc file in and redo the beamforming/parcellation very easily.

**Comment by matsvanes** [comment]
I agree we should leave preproc_file in all functions to allow for flexibility. But perhaps
This line https://github.com/OHBA-analysis/osl/blob/directory-restructure/osl/source_recon/batch.py#L308
Can be replaced?
> if preproc_files is None:
        preproc_files = [None] * n_subjects

```
if preproc_files is None:
    preproc_files = [os.path.join(outdir, subject, subject + 'preproc_raw.fif') for subject in subjects]
    # test whether files exist
    preproc_files = [preproc_file if os.path.exists(preproc_file) else None for preproc_file in preproc_files]

if epoch_files is None: # might want to include a user option for turning "on" source recon for preproc/epochs
    epoch_files = [os.path.join(outdir, subject, subject + 'epochs.fif') for subject in subjects]
    # test whether files exist
    epoch_files = [epoch_file if os.path.exists(epoch_file) else None for epoch_file in epoch_files]
```

**Comment by matsvanes** [comment]
Does the reportdir always need to be passed in source_recon functions?
i.e., https://github.com/OHBA-analysis/osl/blob/directory-restructure/osl/source_recon/batch.py#L189
Only asking because this means that custom functions will need to have `reportdir` as an input variable, which we need to document properly

**Comment by cgohil8** [comment]
New features to do:
- Make `preproc_files`/`epoch_files`/`smri_files` option in `run_src_batch`.
- Add a decorator (or something else) allows us to handle passing any args/kwargs.

**Pull request merged**
